dfds/terraform-grafana-cloud

grafana_dashboard/main.tf
Here is a little subset of terraform state:
```
module.dashboards.grafana_dashboard.this[0]
module.dashboards.grafana_dashboard.this[1]
module.dashboards.grafana_dashboard.this[2]
module.dashboards.grafana_dashboard.this[3]
```
As I suspected: when reading the dashboards from disk, it is done so alphabetically .
Assume module.dashboards.grafana_dashboard.this[1] is a dashboard for a file  that starts with a 'B' and
module.dashboards.grafana_dashboard.this[2] iss a dashboard for a file  that starts with a 'L'
Let's say I need to add a new dashboard that starts with a 'C', then Terraform state will try to insert the new dashboard into state between [1] and [2].
Hence [2] becomes [3], [3] becomes [4] and so.....and that is why the plan will attempt to update the next dashboard in a list and …
=> Change from looping over list to looping over map in order to fix TF state conflicts in new content

grafana_alert/main.tf, grafana_alert/variables.tf, grafana_alert/versions.tf
adding alert module to read alert json files
=> enable creating alerts from json files in folder

.github/workflows/tfsec.yaml
replace tfsec with trivy based on recommendation from aqua
=> trivy instead of tfsec

README.md, providers.tf, stack.tf, variables.tf
Enables creating teams. Part of: https://github.com/dfds/cloudplatform/issues/2788
=> Allow creating teams

README.md, outputs.tf, providers.tf, stack.tf, variables.tf
Part of: https://github.com/dfds/cloudplatform/issues/2755
=> Add multi-stack token

README.md, grafana_data_source/main.tf, grafana_data_source/variables.tf, grafana_data_source/versions.tf, outputs.tf
Part of: https://github.com/dfds/cloudplatform/issues/2755
=> Add grafana_data_source submodule

grafana_notification/main.tf, grafana_notification/variables.tf, grafana_notification/versions.tf
Related to issue https://github.com/dfds/cloudplatform/issues/2801
=> Add Slack integration. Also prepare for setting up a policy once we have our own stack

README.md, stack.tf, variables.tf
SAML feature support 
issue: https://github.com/dfds/cloudplatform/issues/2780
=> SSO Saml feature support added

README.md, outputs.tf, stack.tf, variables.tf
=> more outputs for otlp. remove redundant token

grafana_notification/main.tf
Prevent 24h alerts getting grouped together
=> fix: amend 24h grouping

stack.tf
This PR enable loading recording rules, alert config and profiles into other stacks
=> data source read only token scope updated

README.md, otel-collector.tf, otel-collector/values.yaml, variables.tf, versions.tf
=> wip: otel collector

README.md, stack.tf
=> write otlp to param store

otel-collector.tf, otel-collector/values.yaml
ensure user friendly internal dns name for collectors
=> collector svc name based on cname. resource label added

README.md, outputs.tf
output stack slug for dependency support in the consuming module
part of solving this https://github.com/dfds/cloudplatform/issues/2908
=> output stack slug for dependency support

grafana_data_source/main.tf, grafana_data_source/variables.tf
Enable setting the default option on data sources
=> enable setting default option on data sources

README.md, onepassword-item.tf, stack.tf, variables.tf
Dedicated service account user with fine-grained permissions for stack editors
Requires passing serivce_account_editor_permissions
=> creating resources for service account for stack editors

README.md, onepassword-item.tf, stack.tf, variables.tf
fix sa editor provisioning and provided correct user ids for stack
=> fix editor sa and 1password items

grafana_alert/versions.tofu, grafana_dashboard/versions.tofu, grafana_data_source/versions.tofu, grafana_data_source_athena/versions.tofu, grafana_data_source_cloudwatch/versions.tofu, grafana_folder/versions.tofu, grafana_notification/versions.tofu, grafana_synthetic_check/versions.tofu, renovate.json
Now it supports both Terraform and OpenTofu
https://github.com/dfds/cloudplatform/issues/2852
=> Allow using OpenTofu 1.8 and higher

otel-collector.tf, otel-collector/values.yaml, providers.tf
issue: https://github.com/dfds/cloudplatform/issues/2969
=> toggle for collectors

README.md, grafana_prometheus_rules/main.tf, grafana_prometheus_rules/variables.tf, grafana_prometheus_rules/versions.tf, grafana_prometheus_rules/versions.tofu, stack.tf
Add a module for loading Prometheus rules. 
Save Prometheus URL and user id to SSM
=> Add a module for loading Prometheus rules. Save Prometheus URL and user id to SSM

grafana_alert/main.tf
fixing failed pipeline for issue https://github.com/dfds/cloudplatform/issues/3042
=> fix add interval conversion in grafana_rule_group and add support for days

onepassword-item.tf, stack.tf
Enable using prometheus token for reading metrics for opencost 
Ticket #250230479
=> enable read-write on prom write tokens
